### ISSUE TITLE
Scripting against the API

### ISSUE THREAD

**Issue by timrobertson100** [gbif/metabarcoding-data-toolkit-backend#5]
The idea to script against the MDT API has come up in the MDP to support bulk export from a system and get the data into the MDT.

It would be an interesting experiment to see how easy one could script an upload, post a data mapping and trigger a process to create the datasets. This will of course require very consistently formatted input files to be repeatable. 

If this is feasible, can we document a process to explore the potential?

**Comment by timrobertson100** [comment]
I wonder if we can just record the traffic from a browser session to capture the requests sent and turn that into a document?

**Comment by thomasstjerne** [comment]
See [this example](https://github.com/gbif/metabarcoding-data-toolkit-backend?tab=readme-ov-file#api)
